POST http://localhost:8000/admin/cards/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ2YTg2ZGM0ZjY5ZmIzOTcxZGE0NDciLCJpYXQiOjE2OTkxMjk0NTMsImV4cCI6MTcwMTcyMTQ1M30.ErDJ1aDLq82BiT0IebZvpgMWhZX3nFa0_Db_QBrgJ10

{
    "name": "Лучшая колода для новичков",
    "description": "Такие-то условия работы колоды, возможно реализовтаь при определенных случаях, акцентировать улучшение способности 'Восхождение' у мага",
    "imageUrl": "https://music.yandex.ru/home",
    "abilities": [
    {
      "name": "Способность 1",
      "description": "Описание способности 1",
      "level": 1
    },
    {
      "name": "Способность 2",
      "description": "Описание способности 2",
      "level": 2
    },
    {
      "name": "Способность 3",
      "description": "Описание способности 3",
      "level": 3
    }
    ]
}